### ISSUE TITLE
Linking spotify's random to random PHP

### ISSUE THREAD

**Issue by k-z-m-r** [cse442-spring-2020-offering/cse442-project-purehtml#113]
As a developer I want to link our random scripts to that of the random.php frontend so that each call for a random song gives a new one.

Functionality:
- calling the random button pings 'get_random.php' which takes advantage of session variables to pull a complete list of all tracks.
- this takes a random index from the size of that array and returns the element associated with that index.
- for now, we just print the spotify URI of that song (basically, the combinatronic string associated with that song)

Task tests:
- after making some arbitrary search, say Kanye West, hit the random button
- upon clicking, this will take some time to load but will eventually bring the user to the random page
- this will display a random string of that song ID 
- if the same search is made again (or the page is backed up), the song ID will be different.  

This leads up to us implementing Spotify's HTML options to actually display the song inline.

**Comment by Aritra-Paul** [comment]
Doesn't depend on a User Story
